[package]
edition = "2021"
name = "schema"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
db_dep = {path = "../db_dep"}
surrealdb-schema-derive = {path = "../patch/surrealdb-schema-derive"}
# surrealdb-schema-derive={git="https://github.com/KeatonTech/surrealdb-schema-derive"}
once_cell = "^1.15.0"
# surreal-simple-querybuilder = {path = "../patch/surreal-simple-querybuilder"}
insta = "1.21.0"
